WITH RECURSIVE HOUR AS( -- 가상 테이블 만들기 0부터 23까지 반복
    SELECT 0 AS H
    UNION ALL
    SELECT H+1 FROM HOUR 
    WHERE H<23
)
SELECT H AS HOUR, COUNT(DATETIME) AS COUNT
FROM HOUR AS H LEFT JOIN ANIMAL_OUTS
ON H.H=HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOUR
ORDER BY HOUR;